# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  jest-tests:
    docker:
      - image: circleci/node:13.5.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run: 
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run: 
          name: Run Tests
          command: |
            JEST_JUNIT_OUTPUT_DIR="./test_results/jest" \
            yarn test \
            --ci \
            --reporters="default" \
            --reporters="jest-junit" \


      - store_test_results:
          path: ./test_results

  cypress-tests:
    docker:
      - image: cypress/base:13.3.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
            - /root/.cache/Cypress
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Tests
          command: |
            yarn test:cypress:ci

      - store_test_results:
          path: ./test_results

      - store_artifacts:
          path: cypress/videos/
          destination: cypress-videos

      - store_artifacts:
          path: cypress/screenshots/
          destination: cypress-screenshots

workflows:
  version: 2
  test:
    jobs:
      - jest-tests
      - cypress-tests
